use_frameworks!

platform :ios, '8.0'

target 'KMScanner_Example' do
#    pod 'KMScanner', :path => '../'
    pod 'KMScanner'
    target 'KMScanner_Tests' do
    inherit! :search_paths

    
  end
end
